export const IDENTIFIER = {
  Logger: Symbol.for('Logger'),
  Application: Symbol.for('Application'),
  HttpService: Symbol.for('HttpService'),
  RedisService: Symbol.for('RedisService'),
  MongooseService: Symbol.for('MongooseService'),
  PasswordService: Symbol.for('PasswordService'),
  JWTService: Symbol.for('JWTService'),
  Routes: Symbol.for('Routes'),
  PropertyRoutes: Symbol.for('PropertyRoutes'),
  UserRoutes: Symbol.for('UserRoutes'),
  AuthRoutes: Symbol.for('AuthRoutes'),
  AuthenticationService: Symbol.for('AuthenticationService'),
  AuthController: Symbol.for('AuthController'),
  BasicMiddleware: Symbol.for('BasicMiddleware'),
  ValidateMiddleware: Symbol.for('ValidateMiddleware'),
  ErrorHandlerMiddleware: Symbol.for('ErrorHandlerMiddleware'),
  AuthorizationMiddleware: Symbol.for('AuthorizationMiddleware'),
  UserRepository: Symbol.for('UserRepository'),
  UserController: Symbol.for('UserController'),
  UserService: Symbol.for('UserService'),
  PropertyService: Symbol.for('PropertyService'),
  PropertyRepository: Symbol.for('PropertyRepository'),
  PropertyController: Symbol.for('PropertyController'),
  GeoCodingService: Symbol.for('GeoCodingService'),
  SearchQueryFactory: Symbol.for('SearchQueryFactory'),
  RadiusLatLangSearch: Symbol.for('RadiusLatLangSearch')
}